MilitaryCollege/Controllers/OfficersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MilitaryCollege.Models;
using MilitaryCollege.Models.ViewModels;
using NSubstitute;

namespace MilitaryCollege.Controllers
{
    [Authorize]
    public class OfficersController : Controller
    {
        private readonly MilitaryContext _context;
        private IWebHostEnvironment _appEnvironment;
        // to access user and check which user logged in
        private IHttpContextAccessor _httpContextAccessor;
        private readonly UserManager<IdentityUser> _userManager;


        private FileManagementController _fileManagementController;

        public OfficersController(MilitaryContext context, IWebHostEnvironment appEnvironment , IHttpContextAccessor httpContextAccessor, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _appEnvironment = appEnvironment;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
        }

        // GET: Officers
        public async Task<IActionResult> Index(int ? id)
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            // tournament Id assigned to current user Id 
            int? TournamentId = _context.UserTournaments.Where(u => u.UserId == userId).Select(t => t.TournamentId).FirstOrDefault();
            var user = await _userManager.FindByIdAsync(userId);

            if (await _userManager.IsInRoleAsync(user, "SuperAdmin") || await _userManager.IsInRoleAsync(user, "Viewer"))
            {
                TournamentId = id != 0 ? id : TournamentId;
            }
            return View(await _context.Officers.Where(o => o.IsActive && o.TournamentId == TournamentId).OrderBy(o => o.MilitaryNumber).ToListAsync());
        }

        public async Task<IActionResult> OfficerListOfcard(int ? Tid)
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            // tournament Id assigned to current user Id 
            int? TournamentId = _context.UserTournaments.Where(u => u.UserId == userId).Select(t => t.TournamentId).FirstOrDefault();
            var user = await _userManager.FindByIdAsync(userId);

            // if click on tournament show all officer inside it only for General and colonel abou daher and superadmin
            if (await _userManager.IsInRoleAsync(user, "SuperAdmin") || await _userManager.IsInRoleAsync(user, "Viewer"))
            {
                TournamentId = Tid != 0 ? Tid : TournamentId;
            }


                return View(await _context.Officers.Where(o => o.IsActive && o.TournamentId == TournamentId).OrderBy(o=>o.MilitaryNumber).ToListAsync());
        }
        [Authorize(Roles = "SuperAdmin , Admin , Officer ,Viewer ,AdminInvT")]

        // GET: Officers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var officer = await _context.Officers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (officer == null)
            {
                return NotFound();
            }
            OfficerVM officerVM = new OfficerVM()
            {
                Id = officer.Id,
                Name = officer.Name,
                ExistingImage = officer.ProfileImage,
                MilitaryNumber = officer.MilitaryNumber,
                Email = officer.Email,
                PhoneNumber = officer.PhoneNumber,
                BirthAddress = officer.BirthAddress,
                Address = officer.Address,
                BirthDate = officer.BirthDate,
                Nationality = officer.Nationality,
                BloodType = officer.BloodType,
                Height = officer.Height,
                PreviousJob = officer.PreviousJob,
                HealthProblem = officer.HealthProblem,
                RatingEnteringYear = officer.RatingEnteringYear,
                RatingEnteringNumber = officer.RatingEnteringNumber,
                Specialization = officer.Specialization,
                RatingGradutionYear = officer.RatingGradutionYear,
                RatingGradutionNumber = officer.RatingGradutionNumber,
                Notes = officer.Notes
            };
            officerVM.EducationalAttainments = _context.EducationalAttainments.Where(o => o.OfficerId == officerVM.Id).ToList();
            officerVM.Languages = _context.Languages.Where(o => o.OfficerId == officerVM.Id).ToList();
            officerVM.Hobbies = _context.Hobbies.Where(o => o.OfficerId == officerVM.Id).ToList();
            officerVM.DailyIncidentents = _context.DailyIncidents.Where(o => o.OfficerId == id).OrderBy(s => s.StartDate).Include(r => r.ReasonOfIncident).ToList();
            int SumOfTotalDaysInIncidents = 0;
            foreach (var item in officerVM.DailyIncidentents)
            {
                SumOfTotalDaysInIncidents += item.CountDaysOfIncident;
            }

            // count of incidents for an officer 
            officerVM.TotalCountOfIncidentsForOfficer = officerVM.DailyIncidentents.Count;
            // sum of total days of incidents
            officerVM.SumOfDaysInIncidentsForOfficer = SumOfTotalDaysInIncidents;

            officerVM.DailyNotes = _context.DailyNotes.Where(o => o.OfficerId == id).OrderBy(s => s.CreationDate).ToList();

            return View(officerVM);
        }

        // GET: Officers/Create
        [Authorize(Roles = "SuperAdmin ,Admin,User , AdminInvT")]
        public IActionResult Create(OfficerVM officerVM)
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            // tournament Id assigned to current user Id 
            int TournamentId = _context.UserTournaments.Where(u => u.UserId == userId).Select(t => t.TournamentId).FirstOrDefault();
            Tournament tournament = _context.Tournaments.Where(t=>t.Id == TournamentId).First();
            officerVM.TournamentId = tournament.Id;
            officerVM.TournamentName = tournament.Name;
            officerVM.BirthDate = new DateTime(1995, 1, 1); ;
            return View(officerVM);
        }

        // POST: Officers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OfficerVM officerVM, int TournamnetId)
        {
            // if has an error  on post i keep latest tournament
            var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            // tournament Id assigned to current user Id 
            int TournamentId = _context.UserTournaments.Where(u => u.UserId == userId).Select(t => t.TournamentId).FirstOrDefault();
            Tournament tournament = _context.Tournaments.Where(t => t.Id == TournamentId).First(); officerVM.TournamentId = tournament.Id;
            officerVM.TournamentId = tournament.Id;
            officerVM.TournamentName = tournament.Name;

            if (ModelState.IsValid)
            {
                using (var transaction = _context.Database.BeginTransaction())
                {
                    try
                    {
                        string image = "defaultofficer.png";
                        _fileManagementController = new FileManagementController(_appEnvironment);

                        #region Image
                        //if we uploaded an image
                        if (officerVM.Profileimage != null)
                        {

                            //  #region File Upload Validation
                            bool fileUploadError = _fileManagementController.ValidateFileUploadExtensionAndSize(ModelState, officerVM.Profileimage, FileType.Image, 2);
                            //return error if there is a file upload Error
                            if (fileUploadError)
                            {
                                TempData["message"] = NotificationSystem.AddMessage("لقد حصل خطأ في تحميل الملف", NotificationType.Danger.Value);
                                return View(officerVM);
                            }
                            // upload and remove existing
                            image = _fileManagementController.UploadFile(officerVM.Profileimage, "Media/Officer_Profile");
                        }
                        #endregion

                        // create officer 
                        Officer officer = new Officer()
                        {
                            TournamentId = TournamnetId,
                            Name = officerVM.Name,
                            MilitaryNumber = officerVM.MilitaryNumber,
                            PhoneNumber = officerVM.PhoneNumber,
                            Email = officerVM.Email,
                            BirthAddress = officerVM.BirthAddress,
                            BirthDate = officerVM.BirthDate,
                            Nationality = officerVM.Nationality,
                            Address = officerVM.Address,
                            BloodType = officerVM.BloodType,
                            Height = officerVM.Height,
                            PreviousJob = officerVM.PreviousJob,
                            HealthProblem = officerVM.HealthProblem,
                            RatingEnteringYear = officerVM.RatingEnteringYear,

MilitaryCollege/Views/Shared/_Layout.cshtml
@using MilitaryCollege.Models;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager ;
@using Newtonsoft.Json;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title class="no-print">@ViewData["Title"] - برنامج الكلية الحربية</title>
    @*<link href="~/css/jquery-ui.css" rel="stylesheet" />*@
    <link href="~/lib/jquery-ui-1.12.1/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link href="~/css/font-awesome.min.css" rel="stylesheet" />*@

    <link href="~/css/custom.css" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="~/Media/officer_favicon.png">

</head>
<body class="MilitaryCollegeBody">
    <img class="img_headr_left no-print" src="~/Media/instituteLogo.png" />
    <img class="img_headr_right no-print" src="~/Media/instituteLogo.png" />

    <header class="no-print">
        <div class="container">
            <h1 class="text-center mb-3 headertitle">معهد قوى الأمن الداخلي - كلية الضباط </h1>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <partial name="_Menu" />
                    }

                    <partial name="_LoginPartial" />


                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3 mt-5">

            <div class="msgDiv">
                @if (TempData["message"] != null)
                {
                    NotificationSystem msg = JsonConvert.DeserializeObject<NotificationSystem>((string)TempData["message"]);
                    @Html.Raw(NotificationSystem.GenerateNotification(msg.Message, msg.NotificationType))
                }
            </div>
            @RenderBody()
        </main>
    </div>
    @* jquery 3.3.1 *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/js/jquery-ui.min.js"></script>*@
    <script src="~/lib/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    @* jquery migration has fix autocomplete list under field *@
    <script src="~/js/jquery-migrate-3.0.0.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/global.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>

MilitaryCollege/Views/Shared/_Menu.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
<ul class="HomeMenu navbar-nav mr-1  flex-grow-1">
    @*nav-justified*@
    @if (!User.IsInRole("User"))
    {
        <li class="nav-item ">
            <a class="nav-link TournamentIndexLink" asp-area="" asp-controller="Tournaments" asp-action="Index">الدورات </a>
        </li>

    }

    @if (!User.IsInRole("Viewer") && !User.IsInRole("SuperAdmin"))
    {
        <li class="nav-item ">
            <a class="nav-link OfficerIndexLink" asp-area="" asp-controller="Officers" asp-action="Index">جدول الضباط </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link DailyReportIndexLink" asp-area="" asp-controller="DailyReport" asp-action="Index">التقرير اليومي </a>
        </li>

    }




    @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
    {

        <li class="nav-item ">
            <a class="nav-link DailyReportAdministration" asp-area="" asp-controller="DailyReport" asp-action="AdministrationDailyReportNote"> ادارةالوقوعات </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                التقارير
            </a>
            <div class="dropdown-menu ReportDropdownList" aria-labelledby="navbarDropdownMenuLink">
                <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="PersonelInformationReport">المعلومات الشخصية</a>
                <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="EducationalAttainmentReport">التحصيل العلمي</a>
                <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="LanguagesReport">اللغات</a>
                <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="HobbiesReport">الهوايات</a>
                <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="MilitaryCollegeReport">الكلية الحربية</a>
                <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="AbsenceReport">الغياب</a>
                <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="OfficerDailyNoteReport">السلوك</a>
                <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="OfficerNotesReport">الملاحظات</a>

            </div>
        </li>
    }

    @if(User.IsInRole("AdminInvT"))
    {
    <li class="nav-item ">
        <a class="nav-link DailyReportAdministration" asp-area="" asp-controller="DailyReport" asp-action="AdministrationDailyReportNote"> ادارةالوقوعات </a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            التقارير
        </a>
        <div class="dropdown-menu ReportDropdownList" aria-labelledby="navbarDropdownMenuLink">
            <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="AbsenceReport">الغياب</a>
            <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="OfficerDailyNoteReport">السلوك</a>
            <a class="nav-link dropdown-item" asp-controller="Officers" asp-action="OfficerNotesReport">الملاحظات</a>

        </div>
    </li>
    }


    @if (User.IsInRole("SuperAdmin"))
    {
        <li class="nav-item">
            <a class="nav-link LitsOfRoles" asp-controller="Administration" asp-action="ListOfRoles">Administration </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-lightblue" asp-area="Identity" asp-page="/Account/Register">Register</a>
        </li>


    }


</ul>
}